---
title: "Explanation of Variables"
author: "Ayman Ighwair"
date: "12/11/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Heart disease is the leading cause of death for men, women, and people of most racial and ethnic groups in the United States where one person dies every 37 seconds in the United States from cardiovascular disease. Heart disease describes a range of conditions that affect your heart. Diseases under the heart disease umbrella include blood vessel diseases, such as coronary artery disease, heart rhythm problems (arrhythmias) and heart defects you’re born with (congenital heart defects), among others.

One of the causes of heart disease is high blood pressure which is known to start to cause risk if the Systolic Pressure is of 140 mmHg and  Diastolic  Pressure is 90 mmHg as shown in the formula below : 
$$Hypertension=\frac{140 mmHg}{90 mmHg}$$

In this application, I'll be using machine learning techniques to predict and classify if a patient is suffering from a heart disease or not. 

The app id divided into different tabs.The **Data Discovery** tab gives the user the ability to dig deep into the data using the interactive plots available. 

The **Customized Prediction** tab contains a regression model that allows the user to plug in new predictor values to predict if the patient is going to have a heart disease or not.


The **Knn** tab contains K neartest neighbour classification with options that give the user the ability to change k and check the accuracy rate.

The **download** allows the user to download the heat disease dataset.



A more detailed description of the project, including how the data was collected, is available at <https://archive.ics.uci.edu/ml/datasets/Heart+Disease>.

# Explanation of the variables 
The dataset consists of 303 individuals data. There are 14 columns in the dataset, which are described below.  
 **Age** : displays the age of the individual.  
 **Sex** : displays the gender of the individual using the following format :   
     1 = male  
     0 = female  
  **Chest-pain type**: displays the type of chest-pain experienced by the individual using the following format :  
    1 = typical angina   
    2 = atypical angina   
    3 = non — anginal pain  
    4 = asymptotic  
  **Resting Blood Pressure**: displays the resting blood pressure value of an individual in mmHg (unit)  
  **Serum Cholestrol**: displays the serum cholesterol in mg/dl (unit)  
  **Fasting Blood Sugar**: compares the fasting blood sugar value of an individual with 120mg/dl. If fasting blood sugar > 120mg/dl then :  
    1 (true)   
    0 (false)  
  **Resting ECG** : displays resting electrocardiographic results  
    0 = normal  
    1 = having ST-T wave abnormality  
    2 = left ventricular hyperthrophy  
  **Max heart rate achieved** : displays the max heart rate achieved by an individual. Exercise induced angina :   
    1 = yes  
    0 = no  
  **ST depression induced by exercise relative to rest**: displays the value which is an integer or float.Peak exercise ST segment : 
    1 = upsloping  
    2 = flat  
    3 = downsloping  
  **Number of major vessels (0–3) colored by flourosopy **: displays the value as integer or float.  
  **Thal** : displays the thalassemia :  
    3 = normal  
    6 = fixed defect  
    7 = reversible defect  
  **Diagnosis of heart disease**: Displays whether the individual is suffering from heart disease or not :  
    0 = absence   
    1, 2, 3, 4 = present.  
    
    



